/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yamashiro-r' at '16/05/30 21:59' with Gradle 2.13
 *
 * @author yamashiro-r, @date 16/05/30 21:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
